//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalyomorphaHalys.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugDensityNotification
    {
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> NotificationLatitude { get; set; }
        public Nullable<decimal> NotificationLongitude { get; set; }
        public Nullable<int> NotificationCount { get; set; }
        public Nullable<System.DateTime> NotificationDateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
