//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalyomorphaHalys.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HazelnutBugDbEntities : DbContext
    {
        public HazelnutBugDbEntities()
            : base("name=HazelnutBugDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BugDensityNotification> BugDensityNotifications { get; set; }
        public virtual DbSet<TestImage> TestImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
