
// This file was auto-generated by ML.NET Model Builder. 

using HalyomorphaHalysMLModel_ConsoleTestApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\SAHIN\Desktop\Halyomorpha Halys Research\Image Dataset\anoplophora_chinensis\anoplophora_chinensis001.jpg");
HalyomorphaHalysMLModel.ModelInput sampleData = new HalyomorphaHalysMLModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = HalyomorphaHalysMLModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
